### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by greyli** [z-t-y/LSFD202201V3#2]
Hi Andy，收到你的邮件后这几天大致看了一遍代码，下面是一些可以改进的地方：

## 工厂函数和配置

- Flask 默认为假定模板放到程序示例对应模块同级目录的 templates 文件夹内，所以[这里](https://github.com/z-t-y/LSFD202201/blob/master/__init__.py#L11)不用手动指定 template_folder。
- 既然创建了单独的配置文件，那就把所有配置都集中到这里来，比如工厂函数里[这几行](https://github.com/z-t-y/LSFD202201/blob/master/__init__.py#L13-L15)。

## 获取分页查询参数

获取页数查询参数[这几行](https://github.com/z-t-y/LSFD202201/blob/master/views.py#L35-L38)：

```py
if "page" in request.args:
    page = int(request.args["page"])
else:
    page = 1
```

可以简化为：
```py
page = request.args.get('page', 1, int)  # get(key, default=None, type=None)
```

## 预设置表单内容

在[编辑文章](https://github.com/z-t-y/LSFD202201/blob/master/views.py#L130)这里，因为 CKEditor 通过表单类字段实现，所以预设置编辑器字段值也可以通过给表单字段的 data 属性赋值实现，不需要使用 JavaScript：

```py
form = EditForm()
form.conent = Article().query_by_id(id).content
```

## 表单隐藏字段渲染

因为 CSRF 令牌字段也是隐藏字段（`<input type="hidden">`），所以调用 `form.hidden_tag()` 会同时渲染 CSRF 令牌字段，不需要再调用 `form.csrf_token()`。比如[上传表单](https://github.com/z-t-y/LSFD202201/blob/master/templates/upload.html#L14-L15)这里。

主要就是这些了，都没有实际测试，有些可能没有考虑到你的特殊需求，你再具体确认。

**Comment by andyzhouty** [comment]
template_folder那个不知道为什么在PythonAnywhere端部署的时候报Template not found 错误，所以我手动加了这么一行，居然就没有报错了。
其它的地方都按照你的建议改进了

**Comment by greyli** [comment]
Well done!
